# Generated by Django 2.0.1 on 2018-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'publisher'), (3, 'author'), (4, 'moderator'), (5, 'admin')], default=5),
        ),
    ]
