# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '__first__'),
        ('Author', '0001_initial'),
        ('Publication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.Author', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_description', models.TextField(max_length=500)),
                ('book_image', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(default=255)),
                ('width_field', models.IntegerField(default=255)),
                ('authors', models.ManyToManyField(through='Book.AuthorBook', to='Author.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.Category', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(through='Book.BookCategory', to='Category.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publication.Publication'),
        ),
        migrations.AddField(
            model_name='authorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
    ]
